config/routes.rb
Rails.application.routes.draw do
  # ***** 以下を修正 *****
  root to: "items#index"
  devise_for :users
  resources :items
  # ***** 以上を修正 *****
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  # itemは1人のユーザーに所属する
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # userはたくさんのitemを持っている
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ***** 以下を追加 *****
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end

  # ***** 以上を追加 *****
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
  end

  def create
    current_user.items.create!(item_params)
  end

  # ***** 以下を追記 *****
  private

  def item_params
    params.require(:item).permit(:name, :price)
  end

  # ***** 以上を追記 *****
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # ***** 次を修正 *****
    @items = current_user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
<h1>投稿が完了しました</h1>
<%= link_to "投稿一覧へ戻る", items_path %>

app/views/items/index.html.erb
<h1>購入商品一覧</h1>
<% if user_signed_in? %>
  <% @items.each do |item| %>
    <!-- 三項演算子に修正 " -->
    <p><%= item.name %> : <%= item.price %> : <%= item.user.nickname.present? ? "購入者 #{item.user.nickname}" : "会員No.#{item.user.id}" %></p>
  <% end %>
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/items/new.html.erb
<h1>ご購入商品の情報を入力</h1>
<%= form_with model: @item, local: true do |form| %>
  <p><%= form.label :name, "商品名" %> <%= form.text_field :name %></p>
  <p><%= form.label :price, "値段" %> <%= form.text_field :price %></p>
  <%= form.submit "送信" %>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%# ログイン時 %>
    <%= link_to "トップ", items_path %>
      <%= link_to "投稿画面へ", new_item_path %>
      <!-- ***** マイページのリンクを追加 ***** -->
      <%= link_to "マイページへ", users_path %>
        <!-- ***** 以上を追加 ***** -->
      <%= link_to "アカウント編集", edit_user_registration_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
<% else %>
  <%# 非ログイン時 %>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    < % if user_signed_in?%>
      <%# ログイン時 %>
      <%= link_to "アカウント編集", edit_user_registration_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
      <%= "【ログイン中のアドレス】#{current_user.email}" %>
      < % else %>
        <%# 非ログイン時 %>
        <%= link_to "新規登録", new_user_registration_path, class : "post"%>
        <%= link_to "ログイン", new_user_session_path class : "post"%>
      <% end %>
      <%= yield %>
    </body>
  </html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<% @items.each do |item| %>
  <p><%= item.name %> : <%= item.price %></p>
<% end %>